// src/app/quotes/quotes.component.ts
import { Component } from '@angular/core';
import { Quote } from "../quote.interface";
import { QuotesService } from "../quotes.service";
import { Response } from "@angular/http";

@Component({
  selector: 'app-quotes',
  templateUrl: './quotes.component.html',
  styleUrls: ['./quotes.component.css']
})
export class QuotesComponent {
  quotes: Quote[] = [];

  constructor(private quotesService: QuotesService) {
  }

  onGetQuotes() {
    this.quotesService.getQuotes()
      .subscribe(
        (quotes: Quote[]) => {
          console.log(quotes);
          this.quotes = quotes;
        },
        (error: Response) => alert('Error: ' + error.json().message)
      );
  }

  onDeletedQuote(quote: Quote) {
    const position = this.quotes.findIndex((quoteEl: Quote) => {
      return quoteEl.id == quote.id;
    });
    this.quotes.splice(position, 1);
  }
}

<button class="btn btn-primary" (click)="onGetQuotes()">Get Quotes</button>
<hr>
<app-quote *ngFor="let quote of quotes" [quote]="quote" (quoteDeleted)="onDeletedQuote($event)"></app-quote>

// src/components/quotes.vue
<template>
    <div>
        <button class="btn btn-primary" @click="onGetQuotes">Get Quotes</button>
        <hr>
        <app-quote
                v-for="quote in quotes"
                :qt="quote"
                @quoteDeleted="onQuoteDeleted($event)"></app-quote>
    </div>
</template>

<script>
    import Quote from './quote.vue';
    import axios from 'axios';

    export default {
        data() {
            return {
                quotes: []
            }
        },
        methods: {
            onGetQuotes() {
                axios.get('http://laravel-ng2-vue.dev/api/quotes')
                    .then(
                        response => {
                            this.quotes = response.data.quotes;
                        }
                    )
                    .catch(
                        error => console.log(error)
                    );
            },
            onQuoteDeleted(id) {
                const position = this.quotes.findIndex((element) => {
                    return element.id == id;
                });
                this.quotes.splice(position, 1);
            }
        },
        components: {
            'app-quote': Quote
        }
    }
</script>
