// src/components/signup.vue
<template>
    <form>
        <div class="form-group">
            <label for="username">Username</label>
            <input
                    type="text"
                    id="username"
                    name="username"
                    class="form-control"
                    v-model="username">
        </div>
        <div class="form-group">
            <label for="email">Mail</label>
            <input
                    type="email"
                    id="email"
                    name="email"
                    class="form-control"
                    v-model="email">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input
                    type="password"
                    id="password"
                    name="password"
                    class="form-control"
                    v-model="password">
        </div>
        <button type="submit" class="btn btn-primary" @click.prevent="signup">Signup</button>
    </form>
</template>

<script>
    import axios from 'axios';

    export default {
        data() {
            return {
                username: '',
                email: '',
                password: ''
            }
        },
        methods: {
            signup() {
                axios.post('http://laravel-ng2-vue.dev/api/user',
                    {name: this.username, email: this.email, password: this.password},
                    {headers: {'X-Requested-With': 'XMLHttpRequest'}})
                    .then(
                        (response) => console.log(response)
                    )
                    .catch(
                        (error) => console.log(error)
                    );
            }
        }
    }
</script>

// src/app/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from "@angular/forms";

import { AuthService } from "../auth.service";

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {

  constructor(private authService: AuthService) { }

  ngOnInit() {
  }

  onSignup(form: NgForm) {
    this.authService.signup(form.value.username, form.value.email, form.value.password)
      .subscribe(
        response => console.log(response),
        error => console.log(error)
      );
  }

}

<form (ngSubmit)="onSignup(f)" #f="ngForm">
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" id="username" name="username" ngModel class="form-control" required>
  </div>
  <div class="form-group">
    <label for="email">Mail</label>
    <input type="email" id="email" name="email" ngModel class="form-control" required>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" id="password" name="password" ngModel class="form-control" required>
  </div>
  <button type="submit" [disabled]="!f.valid" class="btn btn-primary">Sign up</button>
</form>
