// src/components/quote.vue
<template>
    <div class="panel panel-default">
        <div class="panel-body">
            {{ qt.content }}
        </div>
        <div class="panel-footer">
            <div v-if="editing">
                <input type="text" v-model="editValue">
                <a @click="onUpdate">Save</a>
                <a @click="onCancel">Cancel</a>
            </div>
            <div v-if="!editing">
                <a @click="onEdit">Edit</a>
                <a @click="onDelete">Delete</a>
            </div>
        </div>

    </div>
</template>

<script>
    import axios from 'axios';

    export default {
        props: ['qt'],
        data() {
            return {
                editing: false,
                editValue: this.qt.content
            }
        },
        methods: {
            onEdit() {
                this.editing = true;
                this.editValue = this.qt.content
            },
            onCancel() {
                this.editing = false;
            },
            onDelete() {
                this.$emit('quoteDeleted', this.qt.id);
                axios.delete('http://laravel-ng2-vue.dev/api/quote/' + this.qt.id)
                    .then(
                        response => console.log(response)
                    )
                    .catch(
                        error => console.log(error)
                    )
            },
            onUpdate() {
                this.editing = false;
                this.qt.content = this.editValue;
                axios.put('http://laravel-ng2-vue.dev/api/quote/' + this.qt.id,
                    {content: this.editValue})
                    .then(
                        response => console.log(response)
                    )
                    .catch(
                        error => console.log(error)
                    );
            }
        }
    }
</script>

<style scoped>
    a {
        cursor: pointer;
    }
</style>

// src/app/quote/quote.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

import { Quote } from "../quote.interface";
import { QuoteService } from "../quote.service";

@Component({
  selector: 'app-quote',
  templateUrl: './quote.component.html',
  styleUrls: ['./quote.component.css']
})
export class QuoteComponent implements OnInit {
  @Input() quote: Quote;
  @Output() quoteDeleted = new EventEmitter<Quote>();
  editing = false;
  editValue = '';

  constructor(private quoteService: QuoteService) { }

  ngOnInit() {
  }

  onEdit() {
    this.editing = true;
    this.editValue = this.quote.content;
  }

  onUpdate() {
    this.quoteService.updateQuote(this.quote.id, this.editValue)
      .subscribe(
        (quote: Quote) => {
          this.quote.content = this.editValue;
          this.editValue = '';
        }
      );
    this.editing = false;
  }

  onCancel() {
    this.editValue = '';
    this.editing = false;
  }

  onDelete() {
    this.quoteService.deleteQuote(this.quote.id)
      .subscribe(
        () => {
          this.quoteDeleted.emit(this.quote);
          console.log('Quote deleted');
        }
      );
  }

}

<div class="panel panel-default">
  <div class="panel-body">
    {{ quote.content }}
  </div>
  <div class="panel-footer">
    <div *ngIf="editing">
      <input type="text" [(ngModel)]="editValue">
      <a href="#" (click)="onUpdate()">Save</a>
      <a href="#" (click)="onCancel()">Cancel</a>
    </div>
    <div *ngIf="!editing">
      <a href="#" (click)="onEdit()">Edit</a>
      <a href="#" (click)="onDelete()">Delete</a>
    </div>
  </div>
</div>
