// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent{

}

<div id="app">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <ul class="nav nav-pills">
          <li role="presentation" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}"><a [routerLink]="['']">Quotes</a></li>
          <li role="presentation" routerLinkActive="active"><a [routerLink]="['/new-quote']">New Quote</a></li>
        </ul>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-xs-12">
        <router-outlet></router-outlet>
      </div>
    </div>
  </div>
</div>

// src/App.vue
<template>
    <div id="app">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <router-link to="/">Quotes</router-link> |
                    <router-link to="/new-quote">New Quote</router-link>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-xs-12">
                    <router-view></router-view>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        data () {
            return {}
        }
    }
</script>

<style>
    #app {
        margin: 30px;
    }
</style>
